### ISSUE TITLE
circleci?

### ISSUE THREAD

**Issue by ke-zhang-rd** [NSLS-II/pyolog2#20]
circleci is activated for this repo's master branch but lacking config.yml. 
Should be deactivate or config it?
I lean to deactivate it since we already have Travis and I didn't see big differences.

**Comment by ke-zhang-rd** [comment]
CircleCi is turn off. CI needs is covered by Trivis

**Comment by danielballan** [comment]
Echoing here on a public channel a comment I made on a private one:

I _think_ this is left over from experiments by @mrakitin involving CircleCI and containers. I am not opposed to continuing those experiments in the future, but until we _have_ a container for the Olog ES server, we can proceed with just TravisCI and VCR.

Thanks for cleaning this up, @ke-zhang-rd. Please comment if I have misunderstood the state of play, @mrakitin.

**Comment by mrakitin** [comment]
I have no memory of enabling CircleCI, and I am not a big fan of it anyway. I think having TravisCI for now is enough. As @danielballan mentioned, it would be great to have a docker image with the server (cc @shroffk), so that we can try to use it for tests, but it can easily be done in TravisCI. A good candidate for the CI platforms is Azure Pipelines, which we can enable later if we need to.
